import type { Props as ProjectLinkProps } from "../components/ProjectLink.astro";

export const allProjects: ProjectLinkProps[] = [
    {
        title: "Design Co Stride 2024",
        image: "path/to/design-co-stride-2024-image.jpg",
        year: "2024",
        organization: "Design Co",
        technologies: ["React", "Next.js", "Tailwind CSS"],
        viewSiteLink: "https://stride24.ucsddesign.co/",
    },
    {
        title: "Triton Fest Fall 24",
        image: "path/to/triton-fest-fall-24-image.jpg",
        year: "2024",
        organization: "UCSD Campus Events",
        technologies: ["React", "Next.js", "Tailwind CSS"],
        viewSiteLink: "https://tritonfest.ucsd.edu/archive/fall24/",
    },
    {
        title: "Design Co Upgrade 2024",
        image: "path/to/design-co-upgrade-2024-image.jpg",
        year: "2024",
        organization: "Design Co",
        technologies: ["React", "Next.js", "Tailwind CSS"],
        viewSiteLink: "https://upgrade24.ucsddesign.co/",
    },
    {
        title: "SGF 2024 Main Site",
        image: "https://edwardnew.netlify.app/sgf.png",
        year: "2024",
        organization: "UCSD ASCE",
        technologies: ["React", "Next.js", "Tailwind CSS"],
        viewSiteLink: "https://sgf.ucsd.edu/",
    },
    {
        title: "SGF 2024 Countdown",
        image: "https://edwardnew.netlify.app/sgf.png",
        year: "2024",
        organization: "UCSD ASCE",
        technologies: ["React", "Next.js", "Tailwind CSS"],
        viewSiteLink: "https://sgf.ucsd.edu/2024/countdown/",
    },
    {
        title: "Design Co Design Frontiers 2024",
        image: "path/to/design-co-design-frontiers-2024-image.jpg",
        year: "2024",
        organization: "Design Co",
        technologies: ["React", "Next.js", "Tailwind CSS"],
        viewSiteLink: "https://df24.ucsddesign.co/",
    },
    {
        title: "Horizon 2024 Main Site",
        image: "https://edwardnew.netlify.app/sgf.png",
        year: "2024",
        organization: "UCSD ASCE",
        technologies: ["Astro"],
        viewSiteLink: "https://ascehorizon.ucsd.edu/",
    },
    {
        title: "Horizon 2024 Countdown",
        image: "https://edwardnew.netlify.app/sgf.png",
        year: "2024",
        organization: "UCSD ASCE",
        technologies: ["Astro"],
        viewSiteLink: "https://ascehorizon.ucsd.edu/archive/2024/countdown/",
    },
    {
        title: "Triton Fest Winter 24",
        image: "path/to/triton-fest-winter-24-image.jpg",
        year: "2024",
        organization: "UCSD Campus Events",
        technologies: ["HTML", "CSS", "JavaScript", "jQuery"],
        viewSiteLink: "https://tritonfest.ucsd.edu/archive/winter24/",
    },
    {
        title: "Triton Fest Fall 23",
        image: "path/to/triton-fest-fall-23-image.jpg",
        year: "2023",
        organization: "UCSD Campus Events",
        technologies: ["HTML", "CSS", "JavaScript"],
        viewSiteLink: "https://tritonfest.ucsd.edu/archive/fall23/",
    },
    {
        title: "SGF 2023 Main Site",
        image: "https://edwardnew.netlify.app/sgf.png",
        year: "2023",
        organization: "UCSD ASCE",
        technologies: ["HTML", "CSS", "JavaScript"],
        viewSiteLink: "https://sgf.ucsd.edu/2023/",
    },
    {
        title: "SGF 2023 Countdown",
        image: "https://edwardnew.netlify.app/sgf.png",
        year: "2023",
        organization: "UCSD ASCE",
        technologies: ["HTML", "CSS", "JavaScript", "Matter.js"],
        viewSiteLink: "https://sgf.ucsd.edu/2023/countdown",
    },
    {
        title: "Horizon 2023 Main Site",
        image: "https://edwardnew.netlify.app/sgf.png",
        year: "2023",
        organization: "UCSD ASCE",
        technologies: ["HTML", "CSS", "JavaScript", "Bootstrap"],
        viewSiteLink: "https://ascehorizon.ucsd.edu/archive/2023/",
    },
    {
        title: "Horizon 2023 Countdown",
        image: "https://edwardnew.netlify.app/sgf.png",
        year: "2023",
        organization: "UCSD ASCE",
        technologies: ["HTML", "CSS", "JavaScript", "Bootstrap"],
        viewSiteLink: "https://ascehorizon.ucsd.edu/archive/2023/countdown",
    },
];

export const comingSoon: ProjectLinkProps[] = [
    {
        title: "SGF 2025 Countdown",
        image: "https://edwardnew.netlify.app/sgf.png",
        year: "2025",
        organization: "UCSD ASCE",
        technologies: ["React", "Next.js", "Tailwind CSS"],
        viewSiteLink: "https://example.com/sgf-2024-main-site",
    },
    {
        title: "Horizon 2025 Countdown",
        image: "https://edwardnew.netlify.app/sgf.png",
        year: "2025",
        organization: "UCSD ASCE",
        technologies: ["React", "Next.js", "Tailwind CSS"],
        viewSiteLink: "https://example.com/sgf-2024-main-site",
    },
    {
        title: "Triton Photography Studio",
        image: "https://edwardnew.netlify.app/sgf.png",
        year: "2025",
        organization: "UCSD Enterprises & Services",
        technologies: ["React", "Next.js", "Tailwind CSS"],
        viewSiteLink: "https://example.com/sgf-2024-main-site",
    },
    {
        title: "OTA Main Site",
        image: "https://edwardnew.netlify.app/sgf.png",
        year: "2025",
        organization: "Out The Archive",
        technologies: ["React", "Next.js", "Tailwind CSS"],
        viewSiteLink: "https://example.com/sgf-2024-main-site",
    },
];
